### ISSUE TITLE
flixel-examples-robovm fails to run on iOS Simulator

### ISSUE THREAD

**Issue by IndrekV** [flixel-gdx/flixel-gdx#86]
Simulator opens up starts the example and crashes right away.

    2015-05-01 00:07:15.851 TiledMap2Demo[22040:329813] [debug] IOSApplication: iOS version: 8.1
    2015-05-01 00:07:15.856 TiledMap2Demo[22040:329813] [debug] IOSApplication: scale: 2.0
    java.lang.NoSuchMethodError:              
    org.robovm.apple.coregraphics.CGRect.size()Lorg/robovm/apple/coregraphics/CGSize;
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication.getBounds(IOSApplication.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication.didFinishLaunching(IOSApplication.java)
	at             com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at org.flixel.TiledMap2DemoIOS.main(TiledMap2DemoIOS.java)

Seems similar to this libgdx issue. https://github.com/libgdx/libgdx/issues/2652
Libgdx version and Robovm version are not in sync.

**Comment by IndrekV** [comment]
@WingEraser Any feedback on this issue?

**Comment by WingEraser** [comment]
The only thing I can say is to use libgdx latest nightly or snapshot, but you'll have to update flixel-gdx too. I don't own a Mac (yet) which makes it harder for to solve this problem. But according the issue you pointed from libgdx it seems to be solved at their side.

**Comment by moly** [comment]
Hi,

Sorry for the delay. I've updated flixel-gdx to the latest libgdx nightly. Hopefully this has fixed your issue.

**Comment by moly** [comment]
Assuming this has been resolved.
